apiVersion: v1
kind: Service
metadata:
  name: miju-app-service
  namespace: default
  labels:
    app: miju-app
spec:
  type: ClusterIP
  selector:
    app: miju-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
